### ISSUE TITLE
Showing current subscription phase on WordPress admin subscriptions overview page is confusing?

### ISSUE THREAD

**Issue by remcotolsma** [wp-pay/core#10]
In the case of a proration phase, this might be confusing?

<img width="1253" alt="Schermafbeelding 2020-09-10 om 15 04 08" src="https://user-images.githubusercontent.com/869674/92732544-e6144500-f376-11ea-824e-e47ad9e3820d.png">

**Comment by rvdsteege** [comment]
Needs to be updated to show first/current regular phase.

**Comment by rvdsteege** [comment]
Fixed.

- Introduced a `get_display_phase()` in https://github.com/wp-pay/core/commit/8dfe29f19d6a6e28f0563cd32baeb5292390517f
- Ignore proration phases in `get_display_phase()` » https://github.com/wp-pay/core/commit/9e9111e3b21da76f2d55007b495a80000751b087
