### ISSUE TITLE
Should subscriptions still have a total amount?

### ISSUE THREAD

**Issue by remcotolsma** [wp-pay/core#11]

**Comment by rvdsteege** [comment]
The total amount depends on the current phase of a subscription. If subscriptions still have a total amount, it might be unclear which amount it represents.

Assuming it represents the regular phase, what would happen when an additional regular phase is added for example?

**Comment by rvdsteege** [comment]
Moved total amount from `PaymentInfo` to `Payment` class in https://github.com/wp-pay/core/commit/255e1083b33e5f5f5093b258b10b8c8c4eb5784b
