### ISSUE TITLE
Highly redundant and secretive CI

### ISSUE THREAD

**Issue by szepeviktor** [wp-pay/core#16]
Hello!
Currently GitHub Actions are set up

1. To run many things many times
1. It is not possible to see whether you fixed a certain test or not - e.g. #15

Please consider copying https://github.com/ergebnis/php-library-template/blob/main/.github/workflows/integrate.yaml

**Comment by szepeviktor** [comment]
The guiding principle is: 1 test/1 CI step.

**Comment by szepeviktor** [comment]
@rvdsteege Thank you for your work.

This is still a mess.
Would you welcome a "1 test/1 CI step" PR?

**Comment by rvdsteege** [comment]
@szepeviktor almost the same as your example and 'still a mess' 😢 😉

You'd like to see PHPCS / PHPMD, PHPStan / Psalm and ESLint / Sass Lint splitted in separate jobs too or any other changes? Feel free to open a PR.
