### ISSUE TITLE
Supported payment method only shows "?"

### ISSUE THREAD

**Issue by knit-pay** [wp-pay/core#18]
Hello, I think there is some issue with below code, it always shows "?" on "Payment Methods" tab of Configuration. It never shows tick or cross (completed/cancelled). Am I doing something wrong?

https://github.com/wp-pay/core/blob/f2c9fcac4b9d83b202ece00dec9774b35877f41e/views/meta-box-gateway-payment-methods.php#L55-L61

**Comment by rvdsteege** [comment]
To be able to determine if a specific payment method is active, the gateway needs to support `get_available_payment_methods()`. See https://github.com/wp-pay-gateways/mollie/blob/2.1.4/src/Gateway.php#L120-L192 for an example integration.

**Comment by knit-pay** [comment]
Please find the attached screenshot where in Mollie payment provider, all the payment methods are marked as "?" instead of "Green Tick"

![image](https://user-images.githubusercontent.com/65900807/92999287-510f7880-f53d-11ea-8311-92fd154f5208.png)

**Comment by rvdsteege** [comment]
Are you using a valid Mollie API key with at least one payment method activated in the Mollie account?

All payment methods that are supported in the plugin for a specific gateway are listed in the gateway settings in WordPress. The checkmark indicates if the method has been activated at the gateway (using the gateway setting to retrieve the currently active payment methods at the gateway, in the earlier mentioned `get_available_payment_methods()`).

**Comment by knit-pay** [comment]
Thanks, it helped.
