### ISSUE TITLE
Add support for payment/transaction connection to subscription periods

### ISSUE THREAD

**Issue by remcotolsma** [wp-pay/core#20]
A payment / transaction can be linked to multiple subscriptions or specific subscription periods. Currently there are no methods available to manage these links.

![db](https://user-images.githubusercontent.com/869674/94151930-462ce000-fe7b-11ea-9ddf-2c39ff6e6a4d.png)

```php
$payment->add_subscription_period( SubscriptionPeriod $period );

$payment->get_subscription_periods() : array

foreach ( $payment->get_subscription_periods() as $subscription_period ) {
    echo $subscription_period->get_start_date()->format( DATE_W3C ), PHP_EOL;
    echo $subscription_period->get_end_date()->format( DATE_W3C ), PHP_EOL;
    echo $subscription_period->get_subscription()->get_description(), PHP_EOL;
}
```

**Comment by rvdsteege** [comment]
Fixed in https://github.com/wp-pay/core/commit/94d88a63ccab8ac777c905b12f95959db95fd3fb
