### ISSUE TITLE
Empty website

### ISSUE THREAD

**Issue by szepeviktor** [wp-pay/core#3]
Could it be that https://www.wp-pay.org/ is empty?

**Comment by rvdsteege** [comment]
That is correct. Please see https://www.pronamic.nl/wordpress/plugins/pronamic-ideal/ and https://www.pronamic.eu/plugins/pronamic-ideal/ or contact us via https://www.pronamic.eu/contact/ if you need any further information.

**Comment by szepeviktor** [comment]
@rvdsteege Thank you.

So wp-pay is still open-source and functional while you sell it as "Pronamic Pay"?

**Comment by rvdsteege** [comment]
The source code on GitHub is fully functional. However, if you decide to use our plugin to accept online payments through your WordPress site, we'd really appreciate it if you purchase a license key. Your purchase allows us to maintain and further develop the plugin — which we actively do.
