### ISSUE TITLE
Need to forward custom field from extension to gateway

### ISSUE THREAD

**Issue by knit-pay** [wp-pay/core#34]
Hello, Is there a way to forward custom filed to a gateway. I know that we can pass customer name, phone, email, address etc to gateway, but I want to know if there is a way by which we can forward a custom filed or data from extension to gateway?

@remcotolsma , @rvdsteege

**Comment by rvdsteege** [comment]
You can hook into the `pronamic_pay_new_payment` action to add meta to the payment (`$payment->set_meta( $key, $value )`). To retrieve the source entry/order, use the source ID from `$payment->get_source_id()`.

In your own gateway, you can retrieve the meta and pass it to the gateway in the `start()` method. In the Pronamic developed gateways, it is not possible to pass custom fields (except for the Mollie gateway, which includes a filter to pass custom metadata to the gateway).
