### ISSUE TITLE
Regarding Hardcoded values in Admin/AdminGatewayPostType.php

### ISSUE THREAD

**Issue by knit-pay** [wp-pay/core#35]
I think these values should be fetched from gateways, instead of hardcoding it here in core. We can use a filter or function to do so. What is your opinion on this?

https://github.com/wp-pay/core/blob/4bd4407a69a4e9047602120b0f6f02ca82e760a7/src/Admin/AdminGatewayPostType.php#L120-L137

and

https://github.com/wp-pay/core/blob/4bd4407a69a4e9047602120b0f6f02ca82e760a7/src/Admin/AdminGatewayPostType.php#L143-L152

**Comment by remcotolsma** [comment]
@knit-pay I agree, can be moved to the corresponding gateway integrations. Is the following setup workable? 

https://github.com/wp-pay-gateways/payvision/commit/b2d0aa5cdd4df147a2137e789ad0c051a1d50c31

**Comment by knit-pay** [comment]
@remcotolsma It's workable, but it's having 3 new methods. Don't you think this little lengthy? Can we reduce the number of functions or steps?

**Comment by remcotolsma** [comment]
True, we introduced a new filter to simplify this: https://github.com/wp-pay/core/commit/f05b776f92defd57ec407016bfb95c1c9b14a082. 

- https://github.com/wp-pay/core#pronamic_gateway_configuration_display_value
- https://github.com/wp-pay/core#pronamic_gateway_configuration_display_value_id

See as an example: https://github.com/wp-pay-gateways/payvision/commit/9ff563ac4398f417b270750161e428ce4e7870d5.

**Comment by knit-pay** [comment]
Thanks
