### ISSUE TITLE
Test Configuration not working with credit card subscription

### ISSUE THREAD

**Issue by knit-pay** [wp-pay/core#37]
Configuration Test option not working for a credit card subscription. Getting below error.
Can not calculate next payment date of subscription without phases.

https://github.com/wp-pay/core/blob/23cc893fee69a7509d3dad6fe73c5ce21bd26303/src/Subscriptions/SubscriptionHelper.php#L208

**Comment by rvdsteege** [comment]
Sorry, I noticed the same issue. Resolved in https://github.com/wp-pay/core/commit/39b0aaa0776b063ecf058ae214f485df1ad4a474
