### ISSUE TITLE
Multi-Select option on Gateway Configuration page.

### ISSUE THREAD

**Issue by knit-pay** [wp-pay/core#43]
Is there a way to create a multi-select input field on the Gateway configuration page? I can't see such an option in meta-box-gateway-settings.php

https://www.w3schools.com/tags/att_select_multiple.asp

https://github.com/wp-pay/core/blob/f5fdc22e6a39071e8f057669b802178515ce3d25/views/meta-box-gateway-settings.php#L381-L390

**Comment by remcotolsma** [comment]
Unfortunately this is currently not possible, but you can define a custom field via a callback.

https://github.com/wp-pay/core/blob/f5fdc22e6a39071e8f057669b802178515ce3d25/views/meta-box-gateway-settings.php#L431-L435

**Comment by knit-pay** [comment]
Thanks for the information.
