### ISSUE TITLE
Fatal error while plugin update

### ISSUE THREAD

**Issue by knit-pay** [wp-pay/core#49]
This fatal error occurs while updating the plugin. This is a temporary error and goes away automatically. Can this be fixed?

An error of type E_ERROR was caused in line 164 of the file /wp-content/plugins/pronamic-ideal/vendor/wp-pay/core/src/Admin/AdminModule.php. Error message: Uncaught Error: Class 'Pronamic\WordPress\Pay\Admin\AdminGatewayPostType' not found in /var/www/html/wp-content/plugins/pronamic-ideal/vendor/wp-pay/core/src/Admin/AdminModule.php:164

**Comment by rvdsteege** [comment]
This sounds like a caching issue (Opcache) in the hosting environment. Closing for now, as we've not received any similar notices about this issue and it is unlikely to be caused by plugin code.
