### ISSUE TITLE
Subscription frequency, times, recurrences, cycles number, maximum renewals

### ISSUE THREAD

**Issue by remcotolsma** [wp-pay/core#7]
Currently we use the term `frequency` to indicate the number of times a subscription date period should repeat. The extensions we support often use different naming conventions for more or less the same thing:

| Term                  | Used by                   |
|-----------------------|---------------------------|
| `frequency`           | [wp-pay/core][1]          |
| `times`               | [Mollie][2]               |
|                       | [Carbon (alias)][3]       |
| `recurrences`         | [PHP DatePeriod][4]       |
|                       | [Carbon][5]               |
| `cycles number`       |                           |
| `total cycles`        | [PayPal][6]               |
| `maximum renewals`    | [Restrict Content Pro][7] |
| `product length`      |                           |
| `limit cycles number` | [MemberPress][8]          |
| `number billing cycles` | [Braintree][9] |

[1]: https://github.com/wp-pay/core/blob/2.3.2/src/Subscriptions/Subscription.php#L42-L52
[2]: https://docs.mollie.com/reference/v2/subscriptions-api/create-subscription
[3]: https://github.com/briannesbitt/Carbon/blob/2.35.0/src/Carbon/CarbonPeriod.php#L48
[4]: https://www.php.net/dateperiod
[5]: https://github.com/briannesbitt/Carbon/blob/2.35.0/src/Carbon/CarbonPeriod.php#L275-L280
[6]: https://developer.paypal.com/docs/api/subscriptions/v1/#definition-billing_cycle
[7]: https://gitlab.com/pronamic-plugins/restrict-content-pro/-/blob/3.3.3/includes/memberships/class-rcp-membership.php#L138-143
[8]: https://github.com/wp-premium/memberpress-business/search?q=limit_cycles_num&unscoped_q=limit_cycles_num
[9]: https://developers.braintreepayments.com/reference/response/plan/ruby#number_of_billing_cycles

It's currently not very clear this `frequency` includes the first period of a subscription. This would also be confusing when the first period is a shorter free trial period. In the PayPal API there is an option to work with `billing_cycles`:

- https://developer.paypal.com/docs/api/subscriptions/v1/#subscriptions_create
- https://developer.paypal.com/docs/api/subscriptions/v1/#definition-billing_cycle

> An array of billing cycles for trial billing and regular billing. A plan can have at most two trial cycles and only one regular cycle.

PayPal also keeps track of cycle executions:

- https://developer.paypal.com/docs/api/subscriptions/v1/#definition-cycle_execution

This currently allows PayPal users to offer 2 trial periods and then a standard period. This setup also allows trail periods that overlap '3' periods.

I think the extensions we currently support only allow the first period to deviate. In most cases it concerns a (free) trial period with a specific length (number day/month/year(s)). But the idea that a subscription period can contain 'sub' periods is not so bad.

**billing_cycles**

```json
"billing_cycles": [
  {
    "frequency": {
      "interval_unit": "MONTH",
      "interval_count": 1
    },
    "tenure_type": "TRIAL",
    "sequence": 1,
    "total_cycles": 2,
    "pricing_scheme": {
      "fixed_price": {
        "value": "3",
        "currency_code": "USD"
      }
    }
  },
  {
    "frequency": {
      "interval_unit": "MONTH",
      "interval_count": 1
    },
    "tenure_type": "TRIAL",
    "sequence": 2,
    "total_cycles": 3,
    "pricing_scheme": {
      "fixed_price": {
        "value": "6",
        "currency_code": "USD"
      }
    }
  },
  {
    "frequency": {
      "interval_unit": "MONTH",
      "interval_count": 1
    },
    "tenure_type": "REGULAR",
    "sequence": 3,
    "total_cycles": 12,
    "pricing_scheme": {
      "fixed_price": {
        "value": "10",
        "currency_code": "USD"
      }
    }
  }
],
```

**cycle_executions**

```json
"cycle_executions": [
  {
    "tenure_type": "TRIAL",
    "sequence": 1,
    "cycles_completed": 0,
    "cycles_remaining": 2,
    "total_cycles": 2
  },
  {
    "tenure_type": "TRIAL",
    "sequence": 2,
    "cycles_completed": 0,
    "cycles_remaining": 3,
    "total_cycles": 3
  },
  {
    "tenure_type": "REGULAR",
    "sequence": 3,
    "cycles_completed": 0,
    "cycles_remaining": 12,
    "total_cycles": 12
  }
]
```

```text
subscription
  periods
    period 1
      name: Trial period 1
      sequence: 1
      recurrences: 3
      frequency:
        interval_unit: MONTH
        interval_count: 1
      periods:
        - month 1
        - month 2
        - month 3
    period 2
      name: Trial period 2
      sequence: 1
      recurrences: 3
      frequency:
        interval_unit: MONTH
        interval_count: 1
      periods:
        - month 1
        - month 2
        - month 3
    period 3
      name: Regular period
      sequence: 1
      recurrences: null
      frequency:
        interval_unit: YEAR
        interval_count: 1
      periods:
        - year 1
        - year 2
        - year 3
```

But how should we name these period definitions?

```php
$subscription->get_period_definitions();

class PeriodDefinition {
  private $sequence;
  private $type;
  private $name;

  /**
   * https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_date-add
   * https://www.php.net/manual/en/dateinterval.construct.php
   * Term: 'period designator'?
   */
  private $interval_unit;
  /**
   * Interval number?
   * Interval count?
   * Interval value?
   * Interval expression?
   */
  private $interval_value;

  private $status;

  private $recurrences;
  private $periods;
  public function get_next_period();
  public function get_number_completed_periods();
  public function get_number_remaining_periods();
  public function is_infinite();
  public function is_completed();
  // https://www.grammarly.com/blog/canceled-vs-cancelled/
  // https://docs.mollie.com/reference/v2/subscriptions-api/cancel-subscription
  public function is_ canceled();
  public function is_trial(); // type == trial
  public function get_interval_date(); // build DateInterval from $interval_
}

$subscription->is_completed(); // check if all period definitions are completed
$subscription->is_infinite(); // check if there is an infinite period definition
$subscription->get_current_period_definition(); // return the first not completed period definition
$subscription->in_trial_period(); // current period is trial
```

**Comment by remcotolsma** [comment]
Maybe we can also use period definitions for synchronized renewals (align renewal schedule) and prorating the first payment.

https://docs.woocommerce.com/document/subscriptions/renewal-synchronisation/

**Comment by remcotolsma** [comment]
RFC in https://github.com/wp-pay/core/commit/25c60dfcbc18b28f588b1fcf61c2bb72d33969be.

**Comment by remcotolsma** [comment]
How should we support prorate first period / amount? One-off period definitions?

```php
$period_definition = new PeriodDefinition( $start_date, $interval_unit, $interval_value, $amount );

$period_definition = new PeriodDefinition( '2020-07-01', 'D', 184, $amount );
$period_definition->set_number_recurrences( 1 );
```

or

```php
$period_definition = new OneOffPeriodDefinition( $start_date, $end_date, $amount );
```

```php
class IntervalPeriodDefinition extends AbstractPeriodDefinition { ... }
class OneOffPeriodDefinition extends AbstractPeriodDefinition { ... }
```

**Comment by rvdsteege** [comment]
I'd go for a `OneOffPeriodDefinition`, seems easier to use.

**Comment by remcotolsma** [comment]
Should we rename `PeriodDefinition` to `Phase` or `SubscriptionPhase`?

https://stripe.com/docs/billing/subscriptions/subscription-schedules

> **Phases**
> When creating a subscription schedule, use the phases attribute to define when changes occur and what properties of the subscription to change. For example, you might offer a coupon for 50% off for the first three months of a subscription. In this scenario, you’d create a subscription schedule where the first phase is three months long and contains the 50% off coupon. In the second phase, the subscription would be reverted to the normal cost and the coupon would be removed. Phases must be sequential, meaning only one phase can be active at a given time.

A subscription can have multiple phases, trail phase, regular phase, etc.?

I think we should do some research on the Stripe API:
https://stripe.com/docs/billing/subscriptions/subscription-schedules/use-cases

**Comment by remcotolsma** [comment]
https://docs.woocommerce.com/document/subscriptions/renewal-synchronisation/

```php
class AlignDetails {

}

SubscriptionPhase::align( $align_details );
```
