### ISSUE TITLE
Can't modify subscription phase amount

### ISSUE THREAD

**Issue by remcotolsma** [wp-pay/core#9]
<img width="1270" alt="Schermafbeelding 2020-09-10 om 15 02 09" src="https://user-images.githubusercontent.com/869674/92732387-ad746b80-f376-11ea-8506-0e7147153b58.png">

**Comment by rvdsteege** [comment]
The ability to manually change the subscription amount has been removed for now.

- https://github.com/wp-pay/core/commit/5a208231acf3abe8d6278d33fd2be9e2d36f9f66
- https://github.com/wp-pay/core/commit/8dfe29f19d6a6e28f0563cd32baeb5292390517f#diff-ab34f179bd5a3b6f13186c65a11307feL87-L98

We'll re-add editing the amount of a subscription (phase) at a later stage.

**Comment by rvdsteege** [comment]
Closed in favour of pronamic/wp-pronamic-pay#151.
